const hostname = `${window.config.domain}:${window.config.port}`
export const HTTP_URL = {
	"resetPassword": `${hostname}/reset_password`,
	"loginVerify": `${hostname}/login_verify`,
	"registerVerify": `${hostname}/register_verify`,
	"lastSign": `${hostname}/last_sign`,
	"goSign": `${hostname}/go_sign`,
	"retrieveOthers": `${hostname}/retrieve_others`,
	"appRelease": `${hostname}/apk/app_release.apk`,
	"checkUpdate": `${hostname}/check_update`,
	"tokenLogin": `${hostname}/token_login`,
	"searchRecord": `${hostname}/search_user_profile\?username=`,
	"checkLog": hostname + "/check_log",
	"updateUserInfo": hostname + '/update_user_info',
	"feedback": hostname + '/feedback',
	"getList": hostname + "/get_list",
	"deleteFile": hostname + "/delete_file/{filename}",
	"uploadFile": hostname + "/Images",
	"downloadFile": hostname + "/Images/{filename}",
	"getLicence": hostname + "/get_licence",
	"getPrivacy": hostname + "/get_privacy",
	"getServiceList": hostname + "/get_service_list",
	"getUserAgreement": hostname + "/get_user_agreement",
	"getAdsConfig": hostname + "/get_ads_config",
	"heartBeat": hostname + "/heart_beat",
	"uploadPic": hostname + "/upload_pic",
	"signRecordTypeahead": hostname + "/sign_record_typeahead?query={query}"
}
